<?php
/**
* @file
* Use this module to learn about Drupal's menu system.
*/
/**
* Implementation of hook_menu().
*/
// function menufun_menu() {
// $items['menufun'] = array(
// 'title' => 'Greeting',
// 'page callback' => 'menufun_hello',
// 'access callback' => TRUE,
// 'type' => MENU_CALLBACK,
// );
// return $items;
// }
// function menufun_menu() {
// $items['menufun'] = array(
// 'title' => 'Menu Fun',
// 'page callback' => 'menufun_greeting',
// 'file' => 'menufun_greeting.inc',
// 'page arguments' => array('Jane', 'Doe'),
// 'access callback' => TRUE,
// 'type' => MENU_NORMAL_ITEM,
// );

// return $items;
// }
// /**
// * Page callback.
// */
// function menufun_hello($first_name = '', $last_name = '') {
// return t('Hello @first_name @last_name',
// array('@first_name' => $first_name, '@last_name' => $last_name));
// }

/**
* Implementation of hook_permission()
*/
// function menufun_permission() {
// return array(
// 'receive greeting' => array(
// 'title' => t('Receive a greeting'),
// 'description' => t('Allow users receive a greeting message'),
// ),
// );
// }
// /**
// * Implementation of hook_menu().
// */
// function menufun_menu() {
// $items['menufun'] = array(
// 'title' => 'Menu Fun',
// 'page callback' => 'menufun_greeting',
// 'file' => 'menufun_greeting.inc',
// 'page arguments' => array('Jane', 'Doe'),
// 'access callback' => 'user_access',
// 'access arguments' => array('receive greeting'),
// 'type' => MENU_NORMAL_ITEM,
// 'weight' => '-1',
// );

// $items['menufun/farewell'] = array(
// 'title' => 'Farewell',
// 'page callback' => 'menufun_farewell',
// 'file' => 'menufun_greeting.inc',
// 'access callback' => 'user_access',
// 'access arguments' => array('receive greeting'),
// 'type' => MENU_NORMAL_ITEM,
// );

// return $items;
// }

function menufun_menu() {
$items['menufun'] = array(
'title' => 'Greeting',
'title callback' => 'menufun_title',
'description' => 'A salutation.',
'page callback' => 'menufun_hello',
'access callback' => TRUE,
);

$items['menufun/farewell'] = array(
'title' => 'Farewell',
'page callback' => 'menufun_farewell',
'file' => 'menufun_greeting.inc',
'access callback' => 'user_access',
'access arguments' => array('receive greeting'),
'type' => MENU_NORMAL_ITEM,
);

return $items;
}

/**
* Page callback.
*/
function menufun_hello() {
return t('Hello!');
}
/**
* Title callback.
*/
// function menufun_title() {
// $now = format_date(time());
// return t('It is now @time', array('@time' => $now));
// }

function menufun_title() {
drupal_set_title(t('The page title'));
$now = format_date(time());
return t('It is now @time', array('@time' => $now));
}