<?php

/**
* 
* Implement hook_permission()
*/

function form_example_permission() {
  return array(
    'submit form_example' => array(
      'title' => t('submit form_example'),
      'description' => t('Submit the form_example form.'),
    ),

  'access form_example submissions' => array(
      'title' => t('Access form_example submissions'),
      'description' => t('Access the form_example submissions.'),
    ),
  );
 }

/**
* Implement hook_menu()
 */

function form_example_menu() {
  $items = array ();
  $items['form_example'] = array(
    'title' => 'My Example Form',
    'page callback' => 'drupal_get_form',
    'access arguments' => array('submit form_example'),
    'type' => MENU_NORMAL_ITEM,
    'page arguments'=> array('form_example_form'),
  );
$items['form_submissions'] = array(
    'title' => 'My Form submissions',
    'page callback' => 'form_example_submissions',
    'access arguments' => array('access form_example submissions'),
    'type' => MENU_NORMAL_ITEM,
    
  );
  
  return $items;
}

/**
* My example form. 
 */
  
  function form_example_form($form,&$form_state) {

 $form['mynumber']=array(
'#type' => 'textfield',
'#title' => t('My number'),
'#size' => 10,
'#maxlength' => 10,
'#required' => TRUE,
'#description' => t('Please enter a valid number'),
);


 $form['mytextfield']=array(
'#type' => 'textfield',
'#title' => t('My textfield'),
'#size' => 60,
'#maxlength' => 128,
'#required' => TRUE,
);

 $form['mytext']=array(
'#type' => 'textarea',
'#title' => t('My text'),
'#required' => TRUE,
'#description' => t('Enter some text'),
'#default_value' => '',
);

 $form['submit']=array(
'#type'=>'submit',
'#value'=>t('Add item'),
);

return $form;
 
}

/**
*Validation handler
 */

function form_example_form_validate($form,&$form_state) {
//print('<pre>'.print_r($form_state['values'],1).'</pre>);die();
if (!is_numeric($form_state['values']['mynumber'])) {
form_set_error('mynumber',t('You must enter a valid number'));
return FALSE;
}
return TRUE;
}

/**
*Submit handler. Enters entry into database
 */

function form_example_form_submit($form,&$form_state) {
$fe_id = db_insert ('form_example')
->fields(array(
'mynumber'=> $form_state['values']['mynumber'],
'mytextfield'=> $form_state['values']['mytextfield'],
'mytext'=> $form_state['values']['mytext'],
))
->execute();

drupal_set_message(t('Your form entry has been added'));
}

/**
* view form submissions
 */

function form_example_submissions() {
  $results = db_query("SELECT * FROM {form_example}");

  $header = array(t('ID'),t('My number'),t('My text field'));
  $rows = array();

  foreach($results AS $result){
   $rows[]=array(
     $result->fe_id,
     $result->mynumber,
     $result->mytextfield,
     $result->mytext,
);
}

 return theme ('table',array('header'=> $header,'rows'=> $rows));

}

